name: run test
description: run service test
inputs:
  service-directory:
    description: the service directory
    required: true
runs:
  using: composite
  steps:
    - id: run-fmt
      working-directory: ${{ inputs.service-directory }}
      uses: actions-rust-lang/rustfmt@v1

    - id: run-test
      shell: bash
      working-directory: ${{ inputs.service-directory }}
      run: |
        echo "running test"
        # cargo test --all-features
