name: build image
description: build docker image
inputs:
  dev-image-name:
    description: Generic build image name
    required: true
  prod-image-name:
    description: Amazon ECR build image name
    required: true
  feature-image-name:
    description: Generic build image name
    required: true
  release-image-name:
    description: Amazon ECR build image name
    required: true
  service-directory:
    description: the service directory
    required: false
    default: .
runs:
  using: composite
  steps:
    - id: build-image
      shell: bash
      env:
        DEV_IMAGE: ${{ inputs.dev-image-name }}
        PROD_IMAGE: ${{ inputs.prod-image-name }}
        RELEASE_IMAGE: ${{ inputs.release-image-name }}
        FEATURE_IMAGE: ${{ inputs.feature-image-name }}
      working-directory: ${{ inputs.service-directory }}
      run: |
        docker build -t ${DEV_IMAGE} -t ${PROD_IMAGE} -t ${RELEASE_IMAGE} -t ${FEATURE_IMAGE} .