name: push ecr
description: publish Docker image to Amazon ECR
inputs:
  ecr-registry:
    description: Amazon ECR registry
    required: true
  ecr-repository:
    description: Amazon ECR repository
    required: true
  dev-image-name:
    description: Generic build image name
    required: true
  prod-image-name:
    description: Amazon ECR build image name
    required: true
runs:
  using: composite
  steps:
    - id: push-ecr
      shell: bash
      env:
        ECR_REGISTRY: ${{ inputs.ecr-registry }}
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        DEV_IMAGE: ${{ inputs.dev-image-name }}
        PROD_IMAGE: ${{ inputs.prod-image-name }}
      run: |
        docker tag ${DEV_IMAGE} ${PROD_IMAGE}
        docker push ${PROD_IMAGE}