name: ssh copy
description: SSH copy local directory to remote server
inputs:
  directory:
    description: the directory to copy
    required: true
  target-directory:
    description: the directory to paste
    required: false
    default: "."
  username:
    description: connect as user
    required: true
  host:
    description: connect to host
    required: true
  port:
    description: connect to port
    required: false
    default: 22
runs:
  using: "composite"
  steps:
    - id: ssh-copy
      shell: bash
      env:
        SOURCE_DIRECTORY: ${{ inputs.directory }}
        TARGET_DIRECTORY: ${{ inputs.target-directory }}
        SSH_USERNAME: ${{ inputs.username }}
        SSH_HOST: ${{ inputs.host }}
        SSH_PORT: ${{ inputs.port }}
      run: |
        rsync -rzP --delete --port=${SSH_PORT} ~/${SOURCE_DIRECTORY} ${SSH_USERNAME}@${SSH_HOST}:${TARGET_DIRECTORY}
