name: build env
description: build environment variables
inputs:
  service-name:
    description: the service name
    required: true
  env:
    description: the environment variable
    required: true
  env-name:
    description: the environment variable
    required: false
  dot-env-key:
    description: dotenv.org env key
    required: false
runs:
  using: composite
  steps:
    - uses: dcarbone/install-jq-action@v2
    - id: build-env
      shell: bash
      env:
        ENV: ${{ inputs.env }}
        SERVICE_NAME: ${{ inputs.service-name }}
      run: |
        mkdir -p ~/${SERVICE_NAME}
        echo ${ENV} | jq \
          -r 'to_entries? | map("\(.key|@text)=\(.value|@text)") | .[]' \
          > ~/${SERVICE_NAME}/env
        cat ~/${SERVICE_NAME}/env
    - id: validate-dot-env
      shell: bash
      env:
        DOTENV_KEY: ${{ inputs.dot-env-key }}
      run: |
        npm install dotenv
        node -e "require('dotenv').config(); console.log(process.env);"
